spin_manifest_version = 2

[application]
name = "aos-p1"
version = "0.1.0"
authors = ["Alex Grieco <awgrieco@gmail.com>"]
description = "Advent of Spin 2023 Problem 1"

[[trigger.http]]
route = "/data"
component = "wish-list"

[component.wish-list]
source = "wish-list/target/wasm32-wasi/release/wish_list.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.wish-list.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "wish-list"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "fileserver"

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "assets", destination = "/" }]
