spin_manifest_version = 2

[application]
name = "challenge-2"
version = "0.1.0"
authors = ["Alex Grieco <awgrieco@gmail.com>"]
description = "Challenge-2"

[[trigger.http]]
route = "/..."
component = "santa-capacity"

[component.santa-capacity]
source = "santa-capacity/target/wasm32-wasi/release/santa_capacity.wasm"
allowed_outbound_hosts = []
[component.santa-capacity.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "santa-capacity"
watch = ["src/**/*.rs", "Cargo.toml"]
